### ISSUE TITLE
android 6.0 红米note4安装app后发现很多功能不可用.

### ISSUE THREAD

**Issue by manuchen** [Vicent9920/MyMap#1]
1.地图选点页面获取不到终点,下方recycleview列表加载不出
2.搜索终点界面,输入关键字无法获取位置
3.左上角返回键不可用
4.因无法获取终点,故无法测试导航功能

**Comment by Vicent9920** [comment]
应该是因为你的手机是6.0的系统，我测试的是红米1  4.4的系统，所以6.0的系统在做没有做运行时权限处理的话，确实不能实现功能。你先将app所需要的权限手动设置后再看看？晚点时间我再处理运行时权限！

**Comment by manuchen** [comment]
是的,我已经自行处理了.为后来者考虑,你可以加一下.

**Comment by Vicent9920** [comment]
最近加完班，我会抽时间来处理一下，，，，，
